# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd src
        cd WIAD
        dotnet restore
    - name: Build
      run: |
        cd src
        cd WIAD
        dotnet build 
        
    - name: pack
      run: |
        cd src
        cd WIAD
        dotnet pack -o test 
        
    - name: artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: nugetRSCG_WhatIAmDoing
        if-no-files-found: error
        retention-days: 1
        path: src/WIAD/test/*.nupkg
        
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
